"""
    CloudEndure API documentation

    © 2021 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\".   # noqa: E501

    The version of the OpenAPI document: 5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cloudendure
from cloudendure.model.compute_location import ComputeLocation
from cloudendure.model.logical_location import LogicalLocation
from cloudendure.model.network_interface import NetworkInterface
from cloudendure.model.outpost import Outpost
from cloudendure.model.security_group import SecurityGroup
from cloudendure.model.storage_location import StorageLocation
from cloudendure.model.subnet import Subnet
globals()['ComputeLocation'] = ComputeLocation
globals()['LogicalLocation'] = LogicalLocation
globals()['NetworkInterface'] = NetworkInterface
globals()['Outpost'] = Outpost
globals()['SecurityGroup'] = SecurityGroup
globals()['StorageLocation'] = StorageLocation
globals()['Subnet'] = Subnet
from cloudendure.model.region import Region


class TestRegion(unittest.TestCase):
    """Region unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegion(self):
        """Test Region"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Region()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
