# coding: utf-8

"""
    CloudEndure API documentation

    © 2017 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\".   # noqa: E501

    OpenAPI spec version: 5
    Contact: https://bit.ly/2T54hSc
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CloudEndureSecurityGroup:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"network_id": "str", "security_group_id": "str", "name": "str"}

    attribute_map = {
        "network_id": "networkId",
        "security_group_id": "securityGroupId",
        "name": "name",
    }

    def __init__(
        self, network_id=None, security_group_id=None, name=None
    ):  # noqa: E501
        """CloudEndureSecurityGroup - a model defined in Swagger"""  # noqa: E501
        self._network_id = None
        self._security_group_id = None
        self._name = None
        self.discriminator = None
        if network_id is not None:
            self.network_id = network_id
        if security_group_id is not None:
            self.security_group_id = security_group_id
        if name is not None:
            self.name = name

    @property
    def network_id(self):
        """Gets the network_id of this CloudEndureSecurityGroup.  # noqa: E501


        :return: The network_id of this CloudEndureSecurityGroup.  # noqa: E501
        :rtype: str
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """Sets the network_id of this CloudEndureSecurityGroup.


        :param network_id: The network_id of this CloudEndureSecurityGroup.  # noqa: E501
        :type: str
        """

        self._network_id = network_id

    @property
    def security_group_id(self):
        """Gets the security_group_id of this CloudEndureSecurityGroup.  # noqa: E501


        :return: The security_group_id of this CloudEndureSecurityGroup.  # noqa: E501
        :rtype: str
        """
        return self._security_group_id

    @security_group_id.setter
    def security_group_id(self, security_group_id):
        """Sets the security_group_id of this CloudEndureSecurityGroup.


        :param security_group_id: The security_group_id of this CloudEndureSecurityGroup.  # noqa: E501
        :type: str
        """

        self._security_group_id = security_group_id

    @property
    def name(self):
        """Gets the name of this CloudEndureSecurityGroup.  # noqa: E501


        :return: The name of this CloudEndureSecurityGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CloudEndureSecurityGroup.


        :param name: The name of this CloudEndureSecurityGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(CloudEndureSecurityGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudEndureSecurityGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
