FROM python:3.8-rc-slim-buster

ARG SYSTEM_PACKAGES="make"

RUN apt-get -qq update && \
    apt-get -qq upgrade && \
    apt-get -qq install ${SYSTEM_PACKAGES}

RUN pip install --upgrade pip && \
    pip install --upgrade wheel setuptools twine pipenv && \
    pipenv install --dev --system --deploy

RUN apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
