"""
    CloudEndure API documentation

    © 2021 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\".   # noqa: E501

    The version of the OpenAPI document: 5
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cloudendure.model_utils import (
    ApiTypeError,
    ModelComposed,  # noqa: F401
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


def lazy_import():
    from cloudendure.model.blueprint_disks import BlueprintDisks
    from cloudendure.model.replication_configuration_replication_tags import (
        ReplicationConfigurationReplicationTags,
    )

    globals()["BlueprintDisks"] = BlueprintDisks
    globals()[
        "ReplicationConfigurationReplicationTags"
    ] = ReplicationConfigurationReplicationTags


class Blueprint(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ("public_ip_action",): {
            "ALLOCATE": "ALLOCATE",
            "DONT_ALLOCATE": "DONT_ALLOCATE",
            "AS_SUBNET": "AS_SUBNET",
        },
        ("security_group_action",): {"FROM_POLICY": "FROM_POLICY",},
        ("tenancy",): {"SHARED": "SHARED", "DEDICATED": "DEDICATED", "HOST": "HOST",},
        ("private_ip_action",): {
            "CREATE_NEW": "CREATE_NEW",
            "COPY_ORIGIN": "COPY_ORIGIN",
            "CUSTOM_IP": "CUSTOM_IP",
            "USE_NETWORK_INTERFACE": "USE_NETWORK_INTERFACE",
        },
        ("static_ip_action",): {
            "EXISTING": "EXISTING",
            "DONT_CREATE": "DONT_CREATE",
            "CREATE_NEW": "CREATE_NEW",
            "IF_IN_ORIGIN": "IF_IN_ORIGIN",
        },
    }

    validations = {}

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            "iam_role": (str,),  # noqa: E501
            "scsi_adapter_type": (str,),  # noqa: E501
            "public_ip_action": (str,),  # noqa: E501
            "machine_name": (str,),  # noqa: E501
            "cpus": (int,),  # noqa: E501
            "security_group_ids": ([str],),  # noqa: E501
            "run_after_launch": (bool,),  # noqa: E501
            "recommended_private_ip": (str,),  # noqa: E501
            "instance_type": (str,),  # noqa: E501
            "mb_ram": (int,),  # noqa: E501
            "network_interface": (str,),  # noqa: E501
            "subnet_ids": ([str],),  # noqa: E501
            "cores_per_cpu": (int,),  # noqa: E501
            "recommended_instance_type": (str,),  # noqa: E501
            "force_uefi": (bool,),  # noqa: E501
            "static_ip": (str,),  # noqa: E501
            "launch_on_instance_id": (str,),  # noqa: E501
            "tags": ([ReplicationConfigurationReplicationTags],),  # noqa: E501
            "security_group_action": (str,),  # noqa: E501
            "private_ips": ([str],),  # noqa: E501
            "tenancy": (str,),  # noqa: E501
            "compute_location_id": (str,),  # noqa: E501
            "subnets_host_project": (str,),  # noqa: E501
            "logical_location_id": (str,),  # noqa: E501
            "network_adapter_type": (str,),  # noqa: E501
            "byol_on_dedicated_instance": (bool,),  # noqa: E501
            "placement_group": (str,),  # noqa: E501
            "machine_id": (str,),  # noqa: E501
            "region": (str,),  # noqa: E501
            "disks": ([BlueprintDisks],),  # noqa: E501
            "private_ip_action": (str,),  # noqa: E501
            "static_ip_action": (str,),  # noqa: E501
            "id": (str,),  # noqa: E501
            "dedicated_host_identifier": (str,),  # noqa: E501
            "use_shared_ram": (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "iam_role": "iamRole",  # noqa: E501
        "scsi_adapter_type": "scsiAdapterType",  # noqa: E501
        "public_ip_action": "publicIPAction",  # noqa: E501
        "machine_name": "machineName",  # noqa: E501
        "cpus": "cpus",  # noqa: E501
        "security_group_ids": "securityGroupIDs",  # noqa: E501
        "run_after_launch": "runAfterLaunch",  # noqa: E501
        "recommended_private_ip": "recommendedPrivateIP",  # noqa: E501
        "instance_type": "instanceType",  # noqa: E501
        "mb_ram": "mbRam",  # noqa: E501
        "network_interface": "networkInterface",  # noqa: E501
        "subnet_ids": "subnetIDs",  # noqa: E501
        "cores_per_cpu": "coresPerCpu",  # noqa: E501
        "recommended_instance_type": "recommendedInstanceType",  # noqa: E501
        "force_uefi": "forceUEFI",  # noqa: E501
        "static_ip": "staticIp",  # noqa: E501
        "launch_on_instance_id": "launchOnInstanceId",  # noqa: E501
        "tags": "tags",  # noqa: E501
        "security_group_action": "securityGroupAction",  # noqa: E501
        "private_ips": "privateIPs",  # noqa: E501
        "tenancy": "tenancy",  # noqa: E501
        "compute_location_id": "computeLocationId",  # noqa: E501
        "subnets_host_project": "subnetsHostProject",  # noqa: E501
        "logical_location_id": "logicalLocationId",  # noqa: E501
        "network_adapter_type": "networkAdapterType",  # noqa: E501
        "byol_on_dedicated_instance": "byolOnDedicatedInstance",  # noqa: E501
        "placement_group": "placementGroup",  # noqa: E501
        "machine_id": "machineId",  # noqa: E501
        "region": "region",  # noqa: E501
        "disks": "disks",  # noqa: E501
        "private_ip_action": "privateIPAction",  # noqa: E501
        "static_ip_action": "staticIpAction",  # noqa: E501
        "id": "id",  # noqa: E501
        "dedicated_host_identifier": "dedicatedHostIdentifier",  # noqa: E501
        "use_shared_ram": "useSharedRam",  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Blueprint - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            iam_role (str): AWS only. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            scsi_adapter_type (str): Currently relevant for vCenter cloud only. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            public_ip_action (str): Whether to allocate an ephemeral public IP, or not. AS_SUBNET causes CloudEndure to copy this property from the source machine.. [optional]  # noqa: E501
            machine_name (str): [optional]  # noqa: E501
            cpus (int): Number of CPUs per per Target machine; Currently relevant for vCenter cloud only; Max value can be fetched from the maxCpusPerMachine property of the Region object. . [optional]  # noqa: E501
            security_group_ids ([str]): AWS only. The security groups that will be applied to the target machine. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            run_after_launch (bool): AWS only. Whether to power on the launched target machine after launch. True by default.. [optional]  # noqa: E501
            recommended_private_ip (str): The private IP address recommended for use with this machine.. [optional]  # noqa: E501
            instance_type (str): Possible values can be fetched from the Region object, plus special values \"COPY_ORIGIN\" or \"CUSTOM\". [optional]  # noqa: E501
            mb_ram (int): MB RAM per Target machine; Currently relevant for vCenter cloud only; Max value can be fetched from the maxMbRamPerMachine property of the Region object. . [optional]  # noqa: E501
            network_interface (str): [optional]  # noqa: E501
            subnet_ids ([str]): AWS only. Configures a subnets in which the instance network interface will take part. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            cores_per_cpu (int): Number of CPU cores per CPU in Target machine; Currently relevant for vCenter cloud only.. [optional]  # noqa: E501
            recommended_instance_type (str): When instance rightsizing is enabled, the instance type suitable for the source machine's HW. [optional]  # noqa: E501
            force_uefi (bool): [optional]  # noqa: E501
            static_ip (str): Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            launch_on_instance_id (str): instance id for target machine managed by AMS.. [optional]  # noqa: E501
            tags ([ReplicationConfigurationReplicationTags]): AWS only. Tags that will be applied to the target machine.. [optional]  # noqa: E501
            security_group_action (str): How to assign a security group to the target machine.. [optional] if omitted the server will use the default value of "FROM_POLICY"  # noqa: E501
            private_ips ([str]): [optional]  # noqa: E501
            tenancy (str): [optional]  # noqa: E501
            compute_location_id (str): [optional]  # noqa: E501
            subnets_host_project (str): GCP only. Host project for cross project network subnet.. [optional]  # noqa: E501
            logical_location_id (str): vcenter = vmFolder; relates to $ref LogicalLocation. [optional]  # noqa: E501
            network_adapter_type (str): Currently relevant for vCenter cloud only. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            byol_on_dedicated_instance (bool): specifies whether to use byol windows license if dedicated instance tenancy is selected.. [optional]  # noqa: E501
            placement_group (str): AWS only. Possible values can be fetched from the Region object.. [optional]  # noqa: E501
            machine_id (str): [optional]  # noqa: E501
            region (str): [optional]  # noqa: E501
            disks ([BlueprintDisks]): AWS only. Target machine disk properties.. [optional]  # noqa: E501
            private_ip_action (str): [optional]  # noqa: E501
            static_ip_action (str): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            dedicated_host_identifier (str): [optional]  # noqa: E501
            use_shared_ram (bool): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                % (args, self.__class__.__name__,),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
