# coding: utf-8

"""
    CloudEndure API documentation

    © 2017 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\".   # noqa: E501

    OpenAPI spec version: 5
    Contact: https://bit.ly/2T54hSc
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from api.replication_api import ReplicationApi  # noqa: E501
from cloudendure import cloudendure_api
from cloudendure.cloudendure_api.rest import ApiException


class TestReplicationApi(unittest.TestCase):
    """ReplicationApi unit test stubs"""

    def setUp(self):
        self.api = api.replication_api.ReplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_project_id_machines_machine_id_bandwidth_throttling_get(self):
        """Test case for projects_project_id_machines_machine_id_bandwidth_throttling_get

        Get value of network bandwidth throttling setting for Machine  # noqa: E501
        """
        pass

    def test_projects_project_id_machines_machine_id_bandwidth_throttling_patch(self):
        """Test case for projects_project_id_machines_machine_id_bandwidth_throttling_patch

        Set value of network bandwidth throttling setting for Machine  # noqa: E501
        """
        pass

    def test_projects_project_id_machines_machine_id_delete(self):
        """Test case for projects_project_id_machines_machine_id_delete

        Uninstall agent  # noqa: E501
        """
        pass

    def test_projects_project_id_machines_machine_id_pointsintime_get(self):
        """Test case for projects_project_id_machines_machine_id_pointsintime_get

        List Available Points-in-time  # noqa: E501
        """
        pass

    def test_projects_project_id_replication_configurations_get(self):
        """Test case for projects_project_id_replication_configurations_get

        List Replication Configurations  # noqa: E501
        """
        pass

    def test_projects_project_id_replication_configurations_post(self):
        """Test case for projects_project_id_replication_configurations_post

        Create Replication Configuration  # noqa: E501
        """
        pass

    def test_projects_project_id_replication_configurations_replication_configuration_id_patch(
        self,
    ):
        """Test case for projects_project_id_replication_configurations_replication_configuration_id_patch

        Modify Replication Configuration  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
